language: java
jdk:
- openjdk8
script: mvn package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LQjeuWdXWoWrwLcASh2h2tzLr9MCyNTE109a+cgpf6lzcAk+foHYqkIwoWRe+3MNnQilRAmE4tuAZ1lklct9iO2ogZLEsEtrqR/rSd0SlxqFsxGf9BPU99ur/Irdi7COh5wFxWnPib2GaDyozrtwOQFBHu++z2CslXSAA4CUTgIitpJMQ2TLV+mvp4RehmFdxw9r2fqTnAi5RosnTu7HdCbh0SjHiu03oW7uG9btxkwM+B4XFldC59S5k85uk0rpd+ks1ZxrYwz+mLhd0aF2hHxU9nIn8TbYjaQAOYiGeXsn9iefJ4qLj3K4mXi7SNLCK1CCVbBCeJ4wSjocgwVM9WIu0Dd0lPHaXhHfRQH4DROPog/CO/a6tUz5GOnUWvxDEgh2D00wJSBLElWaa1JJTD23HE4esCE5KaxDo3eaelqhPnkslPK8eGJucBaEKlplh/gx0SF8XA99R69Y4IsG8eeKH2Q7T8k+9effO1+IyfAhgXoWKjEnt01so8AXalzK0n2igAfYR1XdCWLtoS+6kPdmaQ1LEpfvuDI/6/jNtHPccgdhD0M+tzcuyAXZ94GJO0XiU9/rOXsdhj5vaL8A1Xao+UIhH6g/odykgLyXpyy3CGkEpNtnOyqpGK8nMLmWpZyfitn6uzJsvs1GsbF80NKrlfV96e1prO5113g4108=
  file: "./target/hedwig.zip"
  on:
    tags: true
    all_branches: true
  prerelease: true
